# site
site:
  title: Xenon
  description: ゲームを投稿できるサイトだよ！！
  copyright: © 2018 shioleap

# message
message:
  success:
    saveChanges: 変更を保存しました。
  error:
    notFoundUser: ユーザー名が間違っています。
    notMatchedPassword: パスワードが間違っています。
  validationError:
    # user
    user:
      emptyScreenName: ユーザー名を入力してください。
      isScreenName: 半角英数または_のみで15字以下のユーザー名を入力してください。
      usedScreenName: ユーザー名（%s）はすでに使用されています。
      emptyName: 名前を入力してください。
      isName: 50字以下の名前を入力してください。
      emptyEmail: メールアドレスを入力してください。
      isEmail: メールアドレスのフォーマットが正しくありません。
      usedEmail: メールアドレス（%s）はすでに使用されています。
      emptyPassword: パスワードを入力してください。
      isPassword: 小文字、大文字、数字をそれぞれ含み8字以上のパスワードを入力してください。
      matchedPassword: 同じパスワードを入力してください。
      isDescription: 160字以下の自己紹介を入力してください。
      isUrl: URLの形式かつ255字以下で入力してください。
      isLocation: 30字以下で入力してください。
      emptyAvaterImage: 画像を選択してください。
      isAvaterImage: 10MB 以下の png または jpg の画像を送信してください。
    game:
      emptyTitle: ゲームのタイトルを入力してください
      isTitle: 50字以下のゲームのタイトルを入力してください。
      emptyDescription: ゲームの説明文を入力してください。
      isDescription: 2000字以内のゲームの説明文を入力してください。
      emptyThumbnailImage: 画像を選択してください。
      isThumbnailImage: 10MB 以下の png または jpg の画像を送信してください。
      emptyAppZip: ZIP ファイルを選択してください。
      isAppZip: 10MB 以下の ZIP ファイルを送信してください。

word:
  home: ホーム
  community: コミュニティ
  terms: 利用規約
  privacy: プライバシー
  help: ヘルプ
  contact: お問い合わせ
  category: カテゴリ
  categories: カテゴリ
  tag: タグ
  tags: タグ
  blog: ブログ
  user: ユーザー
  users: ユーザー
  name: 名前
  screenName: ユーザー名
  email: メールアドレス
  password: パスワード
  login: ログイン
  signup: ユーザー登録
  saveChanges: 変更を保存する
  next: 次へ

input:
  user:
    screenNameLabel: ユーザー名
    screenNameTitle: 半角英数または_のみで15字以下
    nameLabel: 名前
    nameTitle: 50字まで
    emailLabel: メールアドレス
    emailTitle: メールアドレス
    publicEmailLabel: メールアドレスの公開
    publicEmailMessage: 誰もがあなたのメールアドレスを見られる状態になります。
    publicEmailString: メールアドレスを全体に公開する
    passwordLabel: パスワード
    passwordTitle: 小文字、大文字、数字をそれぞれ含み8字以上
    passwordConfirmLabel: パスワード（確認）
    passwordConfirmTitle: パスワード（確認）
    currentPasswordLabel: 現在のパスワード
    newPasswordLabel: 新しいパスワード
    newPasswordConfirmLabel: 新しいパスワード（確認）
    newPasswordConfirmTitle: 新しいパスワード（確認）
    descriptionLabel: 自己紹介
    descriptionTitle: 160字まで
    urlLabel: サイト / ブログ
    urlTitle: 255字まで
    locationLabel: 場所
    locationTitle: 30字まで
    avaterImageLabel: プロフィール画像のアップロード
    avaterImageTitle: 10MB までの png または jpeg ファイル
    avaterImageParagraph: 自動で 400(px) x 400(px) に調整されます。
  game:
    titleLabel: ゲームのタイトル
    titleTitle: 50字まで
    tagsLabel: タグ
    tagsTitle: コンマ区切りで10個まで登録可能
    tagsMessage: ゲームに関連付けるタグを10個まで指定できます。タグはコンマ（ , ）で区切って入力してください。<br>（コンマの前後の空白は除去されます。）
    descriptionLabel: ゲームの説明文
    descriptionTitle: 2000字まで
    thumbnailImageLabel: サムネイル画像のアップロード
    thumbnailImageTitle: 10MB までの png または jpeg ファイル
    thumbnailImageParagraph: 自動で 400(px) x 400(px) に調整されます。

# view
view:
  footer:
    about: Xenon について

  login:
    title: ログイン
    header: Xenon にログイン
    message: Xenon のアカウントを持っていない方は<a href="/signup">ユーザー登録</a>
    submitLabel: ログイン

  signup:
    title: ユーザー登録
    header: Xenon へようこそ
    message: 新規登録（無料）して利用をはじめましょう！アカウントをお持ちの方は<a href="/login">ログイン</a>
    submitLabel: 利用規約に同意して登録

  settings:
    account:
      title: アカウント設定
      linkTitle: アカウント
    notifications:
      title: メールアドレスと通知
      linkTitle: メールアドレスと通知
      email: メールアドレス設定
      notifications: 通知設定
    password:
      title: パスワード
      linkTitle: パスワード
    profile:
      title: プロフィール設定
      linkTitle: プロフィール
      profile: プロフィール設定
      avater: プロフィール画像設定

  edit:
    info:
      title: 基本情報
      linkTitle: 基本情報
      info: 基本情報
      thumbnail: サムネイル画像
    app:
      title: ゲーム本体
      linkTitle: ゲーム本体
      app: ゲーム本体のアップロード
    meta:
      title: メタ情報
      linkTitle: メタ情報
      meta: メタ情報の編集
    api:
      title: メタ情報
      linkTitle: API 情報
      api: API キー
    license:
      title: ライセンス
      linkTitle: ライセンス
      license: ライセンス情報の編集
    public:
      title: 公開設定
      linkTitle: 公開設定
      license: 公開設定

  user:
    title: ユーザー
    joinDate: 登録日
