screenName:
  regExp: !!js/regexp '^[a-zA-Z0-9_]{1,15}$'
  string: '^[a-zA-Z0-9_]{1,15}$'
  maxlength: 15
name:
  maxlength: 50
email:
  maxlength: 254
password:
  regExp: !!js/regexp '(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}'
  string: '(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,}'
description:
  maxlength: 160
url:
  maxlength: 2100
location:
  maxlength: 30
